### ISSUE TITLE
Add apk at github release.

### ISSUE THREAD

**Issue by rafiz001** [ImaginativeWorld/Shadhin-Ovidhan-Android#1]
Please add apk file at github's release. It will more helpful to us.

**Comment by ImaginativeShohag** [comment]
Noted.

BTW, the app is in production and available in the play store: https://play.google.com/store/apps/details?id=org.imaginativeworld.shadhinovidhan

**Comment by rafiz001** [comment]
It will help for those who doesn't like play store like me.
