### ISSUE TITLE
Are you planning to upgrade this project?

### ISSUE THREAD

**Issue by kabirnayeem99** [ImaginativeWorld/Shadhin-Ovidhan-Android#2]
It is an old project, I think. It is using a lot of outdated and deprecated libraries and old-school practices. 

Are you planning on upgrading it to newer versions? And implement a new design language like Material You. 

If you plan to do so, I can contribute to this project.

**Comment by ImaginativeShohag** [comment]
I have plans to re-write the whole project from the stretch. So for now don't contribute to it.
